spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/file
    hikari:
      username: db_user
      password: 12345
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: admin123

server:
  port: 6578