spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    hikari:
      username: db_user
      password: 12345
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.example.ecommerce.order.config.kafka.OrderConfirmation
server:
  port: 8070
application:
  config:
    customer-url: http://localhost:8221/api/v1/customer
    payment-url: http://localhost:8221/api/v1/payment
    product-url: http://localhost:8221/api/v1/product



