spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    hikari:
      username: db_user
      password: 12345
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      database: postgresql
      database-platform: org.hibernate.dialect.PostgresSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.example.ecommerce.request.PaymentNotificationRequest
    properties:
      topics:
        payment-topic:
          topic: 'payment_topic'

server:
  port: 8060