spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    hikari:
      username: db_user
      password: 12345
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      database: postgresql
      database-platform: org.hibernate.dialect.PostgresSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.hikari.username}
    password: ${spring.datasource.hikari.password}

server:
  port: 8050

application:
  config:
    file-url: http://localhost:8221/api/v1/file
